# Count the number of lines in a CSV

# import module
import pandas as pd
  
files = ['22ndcenturygroupinc-xxii_shareholders_pipl.csv',
'advancetclimited-atclf_shareholders_pipl.csv',
'allamericanpetcompanyinc-aapt_shareholders_pipl.csv',
'amesiteinc-amst_shareholders_pipl.csv',
'applerushcompanyinc-apru_shareholders_pipl.csv',
'arcimotoinc-fuv_shareholders_pipl.csv',
'augmedixinc-augx_shareholders_pipl.csv',
'aximbiotechnologiesinc-axim_shareholders_pipl.csv',
'betterchoicecompanyinc-bttr_shareholders_pipl.csv',
'betterforyouwellnessinc-bfyw_shareholders_pipl.csv',
'bitdigitalinc-btbt_shareholders_pipl.csv',
'boatiminc-btim_shareholders_pipl.csv',
'bragggaminggroupinc-brggd_shareholders_pipl.csv',
'brookmountexplorationsinc-bmxi_shareholders_pipl.csv',
'caduceussoftwaresystemscorp-csoc_shareholders_pipl.csv',
'canbiolacorp-canb_shareholders_pipl.csv',
'cannabisglobalinc-cbgl_shareholders_pipl.csv',
'cbdglobalsciencesinc-cbdnf_shareholders_pipl.csv',
'coeptistherapeuticsinc-coep_shareholders_pipl.csv',
'cyttacorp-cyca_shareholders_pipl.csv',
'defitechnologiesinc-deftf_shareholders_pipl.csv',
'ecgiholdingsinc-ecgi_shareholders_pipl.csv',
'ecoinnovationgroupinc-ecox_shareholders_pipl.csv',
'ecosciencesinc-ecez_shareholders_pipl.csv',
'ecridinc-ecdd_shareholders_pipl.csv',
'endexxcorporation-edxc_shareholders_pipl.csv',
'eqonexeqos-eqos_shareholders_pipl.csv',
'eqonexltd-eqos_shareholders_pipl.csv',
'fearlessfilmsinc-ferl_shareholders_pipl.csv',
'fourthwaveenergyinc-fwav_shareholders_pipl.csv',
'gaenselenergygroupinc-gegr_shareholders_pipl.csv',
'gamingtechnologiesinc-gmgt_shareholders_pipl.csv',
'gemxcorp-gemz_shareholders_pipl.csv',
'gemxxcorp-gemz_shareholders_pipl.csv',
'geniusbrandsinternationalinc-gnus_shareholders_pipl.csv',
'globexdataltd-skurf_shareholders_pipl.csv',
'globexdataltd-swisf_shareholders_pipl.csv',
'goldentriangleventuresinc-gtvh_shareholders_pipl.csv',
'gpoplusinc-gpox_shareholders_pipl.csv',
'grapheneandsolartechnologiesltd-gstx_shareholders_pipl.csv',
'gtxcorp-gtxo_shareholders_pipl.csv',
'icoainc-icoa_shareholders_pipl.csv',
'iconicbrandsinc-icnb_shareholders_pipl.csv',
'ideanomics-idex_shareholders_pipl.csv',
'ideanomicsinc-idex_shareholders_pipl.csv',
'item9labscorp-inlb_shareholders_pipl.csv',
'joshuagoldresourcesinc-jshg_shareholders_pipl.csv',
'ldmicrocompany-srax_shareholders_pipl.csv',
'lexariabiosciencecorp-lexx_shareholders_pipl.csv',
'lgbtqloyaltyholdingsinc-lfap_shareholders_pipl.csv',
'liveoneinc-lvo_shareholders_pipl.csv',
'magellangoldcorp-mage_shareholders_pipl.csv',
'magellangoldmage-mage_shareholders_pipl.csv',
'majicwheelscorp-mjwl_shareholders_pipl.csv',
'metalertinc-gtxo_shareholders_pipl.csv',
'metamaterialsinc-mmat_shareholders_pipl.csv',
'nexgelinc-nxgl_shareholders_pipl.csv',
'nextecharsolutionscorp-nexcf_shareholders_pipl.csv',
'nurosenehealthinc-mendcnx_shareholders_pipl.csv',
'oncocytecorporation-ocx_shareholders_pipl.csv',
'palatintechnologiesinc-ptn_shareholders_pipl.csv',
'patientaccesssolutionsinc-paso_shareholders_pipl.csv',
'perpetualindustries-prpi_shareholders_pipl.csv',
'pressurebiosciencesinc-pbio_shareholders_pipl.csv',
'qaautomatedregressiontest-zvzzt_shareholders_pipl.csv',
'rainmakerworldwideinc-rakr_shareholders_pipl.csv',
'rayontinc-rayt_shareholders_pipl.csv',
'recruitercomgroupinc-rcrt_shareholders_pipl.csv',
'riotblockchaininc-riot_shareholders_pipl.csv',
'roguestationcompaniesinc-rgst_shareholders_pipl.csv',
'silowellnessinc-silocnx_shareholders_pipl.csv',
'sincerityappliedmaterialsholdingscorpotcpinksinc-sinc_shareholders_pipl.csv',
'smartkeminc-smtk_shareholders_pipl.csv',
'sponsorsoneinc-sponf_shareholders_pipl.csv',
'sraxinc-srax_contacts_ldmicroconf.csv',
'sraxinc-srax_contacts_ldmicroinvitational.csv',
'sraxinc-srax_contacts-ldmain2021.csv',
'sraxinc-srax_shareholders_pipl.csv',
'sraxinc-srax_shareholders_top5.csv',
'sraxir-srax_contacts_ldmicrojune19.csv',
'starallianceinternationalcorp-stal_shareholders_pipl.csv',
'sugarmadeinc-sgmd_shareholders_pipl.csv',
'tautachromeinc-ttcm_shareholders_pipl.csv',
'temasresourcescorp-tmasf_shareholders_pipl.csv',
'transphorminc-tgan_shareholders_pipl.csv',
'twohandsapp-twoh_shareholders_pipl.csv',
'vetanovainc-vtna_shareholders_pipl.csv',
'vivakorinc-vivk_shareholders_pipl.csv',
'wisatechnologiesinc-wisa_shareholders_pipl.csv',
'xindainternationalcorp-xnda_shareholders_pipl.csv'
]

# Counts the numbers of rows on every file in files{}.
for file in files:
    results = pd.read_csv(str(file), sep=',', index_col=False, dtype='unicode', low_memory=False, on_bad_lines='skip')
    #print(str(file))
    print(len(results))